---
- sections:
    - title: Introduction
      link: null
      open: true
      sections:
        - title: Contact Studio Support
          link: docs/introduction/contact-us.md
- sections:
    - title: Getting Started
      link: docs/getting-started.md
      open: true
      sections:
        - title: Setup New Tenant
          link: docs/getting-started/setup-tenant/setup-tenant.md
        - title: Deploy New Tenant
          link: docs/getting-started/setup-tenant/deploy-tenant.md
        - title: Register New Tenant
          link: docs/getting-started/setup-tenant/register-tenant.md
        - title: Code New Tenant
          link: docs/getting-started/code-a-tenant/code-tenant.md
        - title: Preview & Publish Content
          link: docs/getting-started/preview-and-publish-content/preview-and-publish.md
- sections:
    - title: Resources
      link: null
      open: true
      sections:
        - title: API Guidelines
          link: docs/resources/guides/api-guide.md
        - title: how it works
          link: docs/resources/guides/how-to-use-stoplight.md
        - title: Learn how to use Prism Stoplight
          link: docs/resources/guides/how-to-use-stoplight.md
        - title: Learn how to use Docignore
          link: docs/resources/guides/how-to-use-docignore.md
        - title: Tutorials
          link: docs/resources/guides/how-to-use-docignore.md
          open: true
          sections:
            - title: Markdown Support Guide
              link: docs/resources/markdown-support.md
              open: true
              sections:
                - title: Card Support
                  link: docs/tutorials/markdown/card.md
                - title: Tabs Support
                  link: docs/tutorials/markdown/tabs.md
        - title: FAQ
          link: docs/faq/faq.md
- sections:
    - title: TESTING
      link: docs/test.md
