---
- sections:
    - title: Introduction
      sections:
        - title: Contact Studio Support
          link: docs/introduction/contact-us.md
    - title: TransArmor
      open: true
      sections:
        - title: Legacy Data Conversion
          open: true
          link: docs/TransArmor/LegacyDataConversion.md
          access: public
          groups: []
        - title: Network Tokens
          open: true
          link: docs/TransArmor/BulkTokenization.md
          access: public
          groups: []
        - title: P2PE PIMS
          open: true
          sections:
            - title: Equinox
              link: docs/TransArmor/P2PEPIMS/Equinox.md
              access: public
              groups: [TRANSARMOR_P2PE_PIMS]
            - title: ID Tech
              link: docs/TransArmor/P2PEPIMS/IDTech.md
              access: public
              groups: [TRANSARMOR_P2PE_PIMS]
            - title: Ingenico ROAM Mobile
              link: docs/TransArmor/P2PEPIMS/IngenicoROAMMobile.md
              access: public
              groups: [TRANSARMOR_P2PE_PIMS]
            - title: Ingenico Telium2
              link: docs/TransArmor/P2PEPIMS/IngenicoTelium2.md
              access: public
              groups: [TRANSARMOR_P2PE_PIMS]
            - title: Ingenico Tetra
              link: docs/TransArmor/P2PEPIMS/IngenicoTetra.md
              access: public
              groups: [TRANSARMOR_P2PE_PIMS]
            - title: PAX
              link: docs/TransArmor/P2PEPIMS/PAX.md
              access: public
              groups: [TRANSARMOR_P2PE_PIMS]
            - title: Verifone
              link: docs/TransArmor/P2PEPIMS/Verifone.md
              access: public
              groups: [TRANSARMOR_P2PE_PIMS]
    - title: Testing
      open: true
      sections:
        - title: TestingDocs
          link: docs/SpecTest/SpecTest.md
          access: public
          groups: []
- sections:
    - title: Getting Started
      link: docs/getting-started.md
      sections:
        - title: Setup New Tenant
          link: docs/getting-started/setup-tenant/setup-tenant.md
        - title: Deploy New Tenant
          link: docs/getting-started/setup-tenant/deploy-tenant.md
        - title: Register New Tenant
          link: docs/getting-started/setup-tenant/register-tenant.md
        - title: Code New Tenant
          link: docs/getting-started/code-a-tenant/code-tenant.md
        - title: Preview & Publish Content
          link: docs/getting-started/preview-and-publish-content/preview-and-publish.md
- sections:
    - title: Resources
      sections:
        - title: API Guidelines
          link: docs/resources/guides/api-guide.md
        - title: how it works
          link: docs/resources/guides/how-to-use-stoplight.md
        - title: Learn how to use Prism Stoplight
          link: docs/resources/guides/how-to-use-stoplight.md
        - title: Learn how to use Docignore
          link: docs/resources/guides/how-to-use-docignore.md
        - title: Tutorials
          link: docs/resources/guides/how-to-use-docignore.md
          sections:
            - title: Markdown Support Guide
              link: docs/resources/markdown-support.md
              sections:
                - title: Card Support
                  link: docs/tutorials/markdown/card.md
                - title: Tabs Support
                  link: docs/tutorials/markdown/tabs.md
        - title: FAQ
          link: docs/faq/faq.md
- sections:
    - title: TESTING
      link: docs/test.md