################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates.
# Fiserv is a trademark of Fiserv, Inc.,
# registered or used in the United States and foreign countries,
# and may or may not be registered in your country.
# All trademarks, service marks,
# and trade names referenced in this
# material are the property of their
# respective owners. This work, including its contents
# and programming, is confidential and its use
# is strictly limited. This work is furnished only
# for use by duly authorized licensees of Fiserv, Inc.
# or its affiliates, and their designated agents
# or employees responsible for installation or
# operation of the products. Any other use,
# duplication, or dissemination without the
# prior written consent of Fiserv, Inc.
# or its affiliates is strictly prohibited.
# Except as specified by the agreement under
# which the materials are furnished, Fiserv, Inc.
# and its affiliates do not accept any liabilities
# with respect to the information contained herein
# and are not responsible for any direct, indirect,
# special, consequential or exemplary damages
# resulting from the use of this information.
# No warranties, either express or implied,
# are granted or extended by this work or
# the delivery of this work
################################################################################
- filePath: "Payment_Facilitator/Global_SingleMID_PFAC_File_Structure_v3.1.pdf"
  access: private
  groups: [UCOMM_MOBILE_GATEWAY]
- filePath: "uComm_Mobile_Gateway/mg_payment_XSD/mgpayment[1]_140930173404.pdf"
  access: private
  groups: [UCOMM_MOBILE_GATEWAY]
- filePath: "Payment_Facilitator/SampleTest.txt"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "new_folder/readme.md"
  access: private
  groups: []
- filePath: "SpecTest/Test_Equinox_PIMS.pdf"
  access: private
  groups: [UCOMM_MOBILE_GATEWAY]
- filePath: "SpecTest/TestID_Tech_PIMS.pdf"
  access: private
  groups: [BANA]
- filePath: "ProprietaryPlatform/MultiLink_Message_Specification_v4.18.doc"
  access: private
  groups: [MULTILINK_SPECIFICATIONS]
- filePath: "ProprietaryPlatform/MultiLink_Message_Specification_v4_17.docx"
  access: private
  groups: [MULTILINK_SPECIFICATIONS]
- filePath: "ProprietaryPlatform/OffSiteSpec.2221.All.pdf"
  access: private
  groups: []
- filePath: "Reason_Code_Legend.xlsx"
  access: private
  groups: []
- filePath: "South/Test DB Dot.pdf"
  access: private
  groups: [SOUTH]
- filePath: "TransArmor/Fiserv_Bulk_Tokenization_Spec_V2.4.pdf"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "TransArmor/P2PE_v2_PIM_Equinox_Luxe_85xx-RSA_v1.0.pdf"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "TransArmor/P2PE_v2.0_PIM_ID_Tech_SREDKey2 v1.0.pdf"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "TransArmor/P2PE_v3.1_PIM_ING RP45x v1.4.pdf"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "TransArmor/P2PE_v3.1_PIM_Ingenico iSCxxx v1.4.pdf"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "TransArmor/P2PE_v3.1_PIM_ING Lane 3000-Desk 1500 v1.4.pdf"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "TransArmor/P2PE_v2.0_PIM_PAX_A920 v1.0.pdf"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "TransArmor/p2PE_v2.0_PIM_VFI CM5 v1.1.pdf"
  access: private
  groups: [TRANSARMOR_P2PE_PIMS]
- filePath: "TransArmor/LDC-Merchant_Feed_Specification_v2_1.pdf"
  access: private
  groups: []