################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates.
# Fiserv is a trademark of Fiserv, Inc.,
# registered or used in the United States and foreign countries,
# and may or may not be registered in your country.
# All trademarks, service marks,
# and trade names referenced in this
# material are the property of their
# respective owners. This work, including its contents
# and programming, is confidential and its use
# is strictly limited. This work is furnished only
# for use by duly authorized licensees of Fiserv, Inc.
# or its affiliates, and their designated agents
# or employees responsible for installation or
# operation of the products. Any other use,
# duplication, or dissemination without the
# prior written consent of Fiserv, Inc.
# or its affiliates is strictly prohibited.
# Except as specified by the agreement under
# which the materials are furnished, Fiserv, Inc.
# and its affiliates do not accept any liabilities
# with respect to the information contained herein
# and are not responsible for any direct, indirect,
# special, consequential or exemplary damages
# resulting from the use of this information.
# No warranties, either express or implied,
# are granted or extended by this work or
# the delivery of this work
################################################################################
- filePath: "Spec_Testing/Private_Access.pdf"
  access: private
  groups: []
- filePath: "Spec_Testing/Entitled_Access.pdf"
  access: private
  groups: [TEST_GROUP_RG]  
- filePath: "Spec_Testing/Public_Access.pdf"
  access: public
- filePath: "SpecTest/Test_Equinox_PIMS.pdf"
  access: private
  groups: [UCOMM_MOBILE_GATEWAY]  


#   groups: [Test_Group_RG]
# - filePath: "Spec_Testing/Public_Access_no_.pdf"
#   access: public
# - filePath: "Spec_Testing/Private_File_Access_AccessGroupNotSpecified.pdf"
#   access: private
#   groups: []
# - filePath: "Spec_Testing/public_access_But_accessGroup_invalid.pdf"
#   access: public  
#   groups: [Access_Group_not_in_DB]
# - filePath: "Spec_Testing/Public_Access_But_accessGroup_invalid.pdf"
#   access: private  
#   groups: [Access_Group_not_in_DB]
