name: API Specs Validator Action
on:
  # Triggers the workflow on push or pull request events but only for the dev , stage and main branch
  push:
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]
   
jobs:
  call-yaml-validator-from-remote-action: 
    uses: Fiserv/remote-actions/.github/workflows/github-yaml-validator.yaml@develop
  
  call-markdown-validator-from-remote-action: 
    uses: Fiserv/remote-actions/.github/workflows/github-md-validator.yaml@develop    
 
  # call-zip-gen-from-remote-action:
  #   if: github.event_name == 'pull_request'
  #   uses: Fiserv/remote-actions/.github/workflows/github-yaml-validator.yaml@develop
