name: cd
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Experiment
      run: |
        pwd
        ls -la
        mkdir Test-repo
        cd Test-repo
        pwd
        ls -la
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
       repository: Fiserv/Test-repo
    - name: List files in the repository
      run: |
       pwd
       ls -la
