name: Studio Validator
on:
  # Triggers the workflow on push or pull request events but only for the dev , stage and main branch
  push:
    branches: [ develop,stage,main, branch-ruler  ]
  pull_request:
    branches: [ develop,stage,main, branch-ruler ]

jobs:
  validator: 
    uses: Fiserv/remote-actions/.github/workflows/validator-service.yaml@fr-tenant-fix
    secrets: inherit
    with:
      fr-tenant: true
