name: Studio Validator
on:
  workflow_call:
  # Triggers the workflow on push or pull request events but only for the dev , stage and main branch
  push:
    branches: [ develop,stage,main ]
  pull_request:
    branches: [ develop,stage,main ]

# jobs:
#   validator: 
#     uses: Fiserv/remote-actions/.github/workflows/validator-service.yaml@main
jobs:
  MD-Validator-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a '${{ github.commits.modified}} "
        #if: ${{ ((github.ref == 'refs/heads/develop') || (github.ref == 'refs/heads/stage') || (github.ref == 'refs/heads/main')) && (github.event.path == github.workspace/reference/**) }}
