---
name: Webhook Retries
on:
  push:
    branches:
      - develop
jobs:
  retry-webhook-delivery:
    runs-on: ubuntu-latest
    steps:
      - name: Print Commit Information
        run: |
          echo "Event Payload: ${{ toJson(github.event) }}"
        
      
