name: API Specs ZIP Generator Action
on:
  # Triggers the workflow on push request events but only if anything changes into refernce dir. 
  push:
    branches: [ develop,stage,main ]
    paths:
      - 'reference/**' 

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The secret ${{ secrets.YAML_REMOTE_ACTION }} event."