name: API Specs ZIP Generator Action
on:
  # Triggers the workflow on push request events but only if anything changes into refernce dir. 
  push:
    branches: [ develop,stage,main ]
    paths:
      - 'reference/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
    - uses: Fiserv/remote-actions/.github/workflows/github-yaml-validator.yaml@develop